FROM node:16-alpine
WORKDIR '/app'
COPY package.json .
RUN npm install
RUN npm install -g @angular/cli
COPY . .

#CMD ["ng","serve","--host", "0.0.0.0", "--disable-host-check"]
CMD ["ng", "serve", "--host", "0.0.0.0", "--poll=2000", "--port", "4200", "--disable-host-check"]